********* Start testing of tst_ExpectFail *********
Config: Using QTest library @INSERT_QT_VERSION_HERE@, Qt @INSERT_QT_VERSION_HERE@
PASS   : tst_ExpectFail::initTestCase()
QDEBUG : tst_ExpectFail::expectAndContinue() begin
XFAIL  : tst_ExpectFail::expectAndContinue() This should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(65)]
QDEBUG : tst_ExpectFail::expectAndContinue() after
PASS   : tst_ExpectFail::expectAndContinue()
QDEBUG : tst_ExpectFail::expectAndAbort() begin
XFAIL  : tst_ExpectFail::expectAndAbort() This should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(73)]
PASS   : tst_ExpectFail::expectAndAbort()
XFAIL  : tst_ExpectFail::xfailWithQString() A string
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(82)]
XFAIL  : tst_ExpectFail::xfailWithQString() Bug 5 (The message)
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(87)]
PASS   : tst_ExpectFail::xfailWithQString()
XPASS  : tst_ExpectFail::xpass() 'true' returned FALSE. ()
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(93)]
XFAIL  : tst_ExpectFail::dataDrivenTest(Abort) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(126)]
XFAIL  : tst_ExpectFail::dataDrivenTest(Continue) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(126)]
PASS   : tst_ExpectFail::dataDrivenTest()
PASS   : tst_ExpectFail::cleanupTestCase()
Totals: 6 passed, 1 failed, 0 skipped
********* Finished testing of tst_ExpectFail *********
