********* Start testing of tst_ExpectFail *********
Config: Using QTest library @INSERT_QT_VERSION_HERE@, Qt @INSERT_QT_VERSION_HERE@
PASS   : tst_ExpectFail::initTestCase()
QDEBUG : tst_ExpectFail::xfailAndContinue() begin
XFAIL  : tst_ExpectFail::xfailAndContinue() This should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(74)]
QDEBUG : tst_ExpectFail::xfailAndContinue() after
PASS   : tst_ExpectFail::xfailAndContinue()
QDEBUG : tst_ExpectFail::xfailAndAbort() begin
XFAIL  : tst_ExpectFail::xfailAndAbort() This should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(82)]
PASS   : tst_ExpectFail::xfailAndAbort()
FAIL!  : tst_ExpectFail::xfailTwice() Already expecting a fail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(92)]
XFAIL  : tst_ExpectFail::xfailWithQString() A string
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(101)]
XFAIL  : tst_ExpectFail::xfailWithQString() Bug 5 (The message)
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(106)]
PASS   : tst_ExpectFail::xfailWithQString()
XFAIL  : tst_ExpectFail::xfailDataDriven(Abort) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(135)]
XFAIL  : tst_ExpectFail::xfailDataDriven(Continue) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(135)]
PASS   : tst_ExpectFail::xfailDataDriven()
PASS   : tst_ExpectFail::xfailOnWrongRow()
XFAIL  : tst_ExpectFail::xfailOnAnyRow(first row) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(170)]
XFAIL  : tst_ExpectFail::xfailOnAnyRow(second row) This test should xfail
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(170)]
PASS   : tst_ExpectFail::xfailOnAnyRow()
FAIL!  : tst_ExpectFail::xfailWithoutVerify(first row) QEXPECT_FAIL was called without any subsequent verification statements
FAIL!  : tst_ExpectFail::xfailWithoutVerify(second row) QEXPECT_FAIL was called without any subsequent verification statements
XPASS  : tst_ExpectFail::xpass() 'true' returned FALSE. ()
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(190)]
XPASS  : tst_ExpectFail::xpassDataDriven(XPass) 'true' returned FALSE. ()
   Loc: [/home/user/dev/qt5/qtbase/tests/auto/testlib/selftests/expectfail/tst_expectfail.cpp(212)]
PASS   : tst_ExpectFail::cleanupTestCase()
Totals: 8 passed, 5 failed, 0 skipped
********* Finished testing of tst_ExpectFail *********
